; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL	300
@	IN	SOA	arthur-joppart.sb.uclllabs.be. root.arthur-joppart.sb.uclllabs.be. (
			      	420	; Serial
			 	300	; Refresh
			  	300	; Retry
				300	; Expire
			  	300 )	; Negative Cache TTL
;Name servers
arthur-joppart.sb.uclllabs.be.	IN	NS	ns.arthur-joppart.sb.uclllabs.be.
arthur-joppart.sb.uclllabs.be.	IN	NS	ns1.uclllabs.be.
arthur-joppart.sb.uclllabs.be.	IN	NS	ns2.uclllabs.be.
;records

ns	IN	A	193.191.177.133
@	IN	A	193.191.177.133
www	IN	A	193.191.177.133
www1	IN	A	193.191.177.133
www2	IN	A	193.191.177.133
secure	IN	A	193.191.177.133
supersecure	IN	A	193.191.177.133
test	IN	A	193.191.177.254
